<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Platforms>AnyCPU</Platforms>
    <RootNamespace>$(TffrRootNamespace).Testing</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TinyFFR\TinyFFR.csproj" />
    <ProjectReference Include="..\..\Integrations\TinyFFR.Integrations.Common\TinyFFR.Integrations.Common.csproj" />
  </ItemGroup>

</Project>
