// Created on 2024-02-16 by Ben Bowen
// (c) Egodystonic / TinyFFR 2024

namespace Egodystonic.TinyFFR.Environment.Input;

[TestFixture]
class KeyboardOrMouseKeyExtensionsTest {
	[SetUp]
	public void SetUpTest() { }

	[TearDown]
	public void TearDownTest() { }

	[Test]
	public void ShouldCorrectlyCategorizeKeys() {
		KeyboardOrMouseKeyCategory GetExpectedCategory(KeyboardOrMouseKey key) => key switch {
			KeyboardOrMouseKey.Unknown => KeyboardOrMouseKeyCategory.Other,
			KeyboardOrMouseKey.Return => KeyboardOrMouseKeyCategory.Control,
			KeyboardOrMouseKey.Escape => KeyboardOrMouseKeyCategory.Control,
			KeyboardOrMouseKey.Backspace => KeyboardOrMouseKeyCategory.Control,
			KeyboardOrMouseKey.Tab => KeyboardOrMouseKeyCategory.Control,
			KeyboardOrMouseKey.Space => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.ExclamationMark => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.DoubleQuote => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Hash => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Percent => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Dollar => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Ampersand => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.SingleQuote => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.OpeningParenthesis => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.ClosingParenthesis => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Asterisk => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Plus => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Comma => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Minus => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Period => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.ForwardSlash => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.NumberRow0 => KeyboardOrMouseKeyCategory.NumberRow,
			KeyboardOrMouseKey.NumberRow1 => KeyboardOrMouseKeyCategory.NumberRow,
			KeyboardOrMouseKey.NumberRow2 => KeyboardOrMouseKeyCategory.NumberRow,
			KeyboardOrMouseKey.NumberRow3 => KeyboardOrMouseKeyCategory.NumberRow,
			KeyboardOrMouseKey.NumberRow4 => KeyboardOrMouseKeyCategory.NumberRow,
			KeyboardOrMouseKey.NumberRow5 => KeyboardOrMouseKeyCategory.NumberRow,
			KeyboardOrMouseKey.NumberRow6 => KeyboardOrMouseKeyCategory.NumberRow,
			KeyboardOrMouseKey.NumberRow7 => KeyboardOrMouseKeyCategory.NumberRow,
			KeyboardOrMouseKey.NumberRow8 => KeyboardOrMouseKeyCategory.NumberRow,
			KeyboardOrMouseKey.NumberRow9 => KeyboardOrMouseKeyCategory.NumberRow,
			KeyboardOrMouseKey.Colon => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Semicolon => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.LessThan => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Equals => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.GreaterThan => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.QuestionMark => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.AtSymbol => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.LeftSquareBracket => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.BackSlash => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.RightSquareBracket => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Caret => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Underscore => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.Backtick => KeyboardOrMouseKeyCategory.PunctuationAndSymbols,
			KeyboardOrMouseKey.A => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.B => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.C => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.D => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.E => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.F => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.G => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.H => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.I => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.J => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.K => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.L => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.M => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.N => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.O => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.P => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.Q => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.R => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.S => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.T => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.U => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.V => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.W => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.X => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.Y => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.Z => KeyboardOrMouseKeyCategory.Alphabetic,
			KeyboardOrMouseKey.CapsLock => KeyboardOrMouseKeyCategory.Control,
			KeyboardOrMouseKey.F1 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F2 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F3 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F4 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F5 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F6 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F7 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F8 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F9 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F10 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F11 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F12 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.PrintScreen => KeyboardOrMouseKeyCategory.Control,
			KeyboardOrMouseKey.ScrollLock => KeyboardOrMouseKeyCategory.Control,
			KeyboardOrMouseKey.Pause => KeyboardOrMouseKeyCategory.Control,
			KeyboardOrMouseKey.Insert => KeyboardOrMouseKeyCategory.EditingAndNavigation,
			KeyboardOrMouseKey.Home => KeyboardOrMouseKeyCategory.EditingAndNavigation,
			KeyboardOrMouseKey.PageUp => KeyboardOrMouseKeyCategory.EditingAndNavigation,
			KeyboardOrMouseKey.Delete => KeyboardOrMouseKeyCategory.EditingAndNavigation,
			KeyboardOrMouseKey.End => KeyboardOrMouseKeyCategory.EditingAndNavigation,
			KeyboardOrMouseKey.PageDown => KeyboardOrMouseKeyCategory.EditingAndNavigation,
			KeyboardOrMouseKey.ArrowRight => KeyboardOrMouseKeyCategory.Arrow,
			KeyboardOrMouseKey.ArrowLeft => KeyboardOrMouseKeyCategory.Arrow,
			KeyboardOrMouseKey.ArrowDown => KeyboardOrMouseKeyCategory.Arrow,
			KeyboardOrMouseKey.ArrowUp => KeyboardOrMouseKeyCategory.Arrow,
			KeyboardOrMouseKey.NumLock => KeyboardOrMouseKeyCategory.Control,
			KeyboardOrMouseKey.NumpadDivide => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadMultiply => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadMinus => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadPlus => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadEnter => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.Numpad1 => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.Numpad2 => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.Numpad3 => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.Numpad4 => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.Numpad5 => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.Numpad6 => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.Numpad7 => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.Numpad8 => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.Numpad9 => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.Numpad0 => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadPeriod => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.WindowsContextMenu => KeyboardOrMouseKeyCategory.Control,
			KeyboardOrMouseKey.NumpadEquals => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.F13 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F14 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F15 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F16 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F17 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F18 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F19 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F20 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F21 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F22 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F23 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.F24 => KeyboardOrMouseKeyCategory.Function,
			KeyboardOrMouseKey.NumpadComma => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadDoubleZero => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadTripleZero => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadThousandsSeparator => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadDecimalsSeparator => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadCurrencyUnit => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadCurrencySubUnit => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadOpeningParenthesis => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadClosingParenthesis => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadOpeningBrace => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadClosingBrace => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadTab => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.NumpadBackspace => KeyboardOrMouseKeyCategory.Numpad,
			KeyboardOrMouseKey.LeftControl => KeyboardOrMouseKeyCategory.Modifier,
			KeyboardOrMouseKey.LeftShift => KeyboardOrMouseKeyCategory.Modifier,
			KeyboardOrMouseKey.LeftAlt => KeyboardOrMouseKeyCategory.Modifier,
			KeyboardOrMouseKey.LeftWinKey => KeyboardOrMouseKeyCategory.Modifier,
			KeyboardOrMouseKey.RightControl => KeyboardOrMouseKeyCategory.Modifier,
			KeyboardOrMouseKey.RightShift => KeyboardOrMouseKeyCategory.Modifier,
			KeyboardOrMouseKey.RightAlt => KeyboardOrMouseKeyCategory.Modifier,
			KeyboardOrMouseKey.RightWinKey => KeyboardOrMouseKeyCategory.Modifier,
			KeyboardOrMouseKey.MouseLeft => KeyboardOrMouseKeyCategory.Mouse,
			KeyboardOrMouseKey.MouseMiddle => KeyboardOrMouseKeyCategory.Mouse,
			KeyboardOrMouseKey.MouseRight => KeyboardOrMouseKeyCategory.Mouse,
			KeyboardOrMouseKey.Mouse4 => KeyboardOrMouseKeyCategory.Mouse,
			KeyboardOrMouseKey.Mouse5 => KeyboardOrMouseKeyCategory.Mouse,
			KeyboardOrMouseKey.MouseWheelUp => KeyboardOrMouseKeyCategory.Mouse,
			KeyboardOrMouseKey.MouseWheelDown => KeyboardOrMouseKeyCategory.Mouse,
			_ => throw new ArgumentOutOfRangeException()
		};

		foreach (var kbmKey in Enum.GetValues<KeyboardOrMouseKey>()) {
			Assert.AreEqual(GetExpectedCategory(kbmKey), kbmKey.GetCategory(), $"Key was {kbmKey}");
			Console.WriteLine($"{kbmKey,30} {(int) kbmKey & ~KeyboardOrMouseKeyExtensions.SdlScancodeToKeycodeBit,-15} {kbmKey.GetCategory()}");
		}
	}

	[Test]
	public void CharBasedValueBitShouldNotClashWithOtherValues() {
		foreach (var kbmKey in Enum.GetValues<KeyboardOrMouseKey>()) {
			Assert.LessOrEqual(((int) kbmKey) & ~(KeyboardOrMouseKeyExtensions.SdlScancodeToKeycodeBit | KeyboardOrMouseKeyExtensions.CharBasedValueBit), KeyboardOrMouseKeyExtensions.CharBasedValueBit);
		}
	}
}