// Created on 2024-01-29 by Ben Bowen
// (c) Egodystonic / TinyFFR 2024

namespace Egodystonic.TinyFFR.Environment.Input;

/* Made to map directly to SDL's SDL_KeyCode
 * For the sake of keeping things simpler for the user and easier to document I don't export every simple key (for example
 * the android buttons, hardware control such as brightness, some extended numpad keys that no modern kb uses to my knowledge, etc.).
 * However I've kept the copy/paste/rename work of those omitted keys in this file commented out in case we want to add them in at a later date
 * or in case someone else wants to build TinyFFR from source and include them.
 */
public enum KeyboardKey : int {
	None = 0,

	Return = '\r',
	Escape = '\x1B',
	Backspace = '\b',
	Tab = '\t',
	Space = ' ',
	ExclamationMark = '!',
	DoubleQuote = '"',
	Hash = '#',
	Percent = '%',
	Dollar = '$',
	Ampersand = '&',
	SingleQuote = '\'',
	OpeningParenthesis = '(',
	ClosingParenthesis = ')',
	Asterisk = '*',
	Plus = '+',
	Comma = ',',
	Minus = '-',
	Period = '.',
	ForwardSlash = '/',
	NumberRow0 = '0',
	NumberRow1 = '1',
	NumberRow2 = '2',
	NumberRow3 = '3',
	NumberRow4 = '4',
	NumberRow5 = '5',
	NumberRow6 = '6',
	NumberRow7 = '7',
	NumberRow8 = '8',
	NumberRow9 = '9',
	Colon = ':',
	Semicolon = ';',
	LessThan = '<',
	Equals = '=',
	GreaterThan = '>',
	QuestionMark = '?',
	AtSymbol = '@',
	LeftSquareBracket = '[',
	BackSlash = '\\',
	RightSquareBracket = ']',
	Caret = '^',
	Underscore = '_',
	Backtick = '`',
	A = 'a',
	B = 'b',
	C = 'c',
	D = 'd',
	E = 'e',
	F = 'f',
	G = 'g',
	H = 'h',
	I = 'i',
	J = 'j',
	K = 'k',
	L = 'l',
	M = 'm',
	N = 'n',
	O = 'o',
	P = 'p',
	Q = 'q',
	R = 'r',
	S = 's',
	T = 't',
	U = 'u',
	V = 'v',
	W = 'w',
	X = 'x',
	Y = 'y',
	Z = 'z',

	CapsLock = 57 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,

	F1 = 58 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F2 = 59 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F3 = 60 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F4 = 61 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F5 = 62 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F6 = 63 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F7 = 64 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F8 = 65 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F9 = 66 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F10 = 67 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F11 = 68 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F12 = 69 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,

	PrintScreen = 70 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	ScrollLock = 71 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Pause = 72 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Insert = 73 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Home = 74 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	PageUp = 75 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Delete = '\x7F',
	End = 77 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	PageDown = 78 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	ArrowRight = 79 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	ArrowLeft = 80 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	ArrowDown = 81 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	ArrowUp = 82 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,

	NumLock = 83 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	
	NumpadDivide = 84 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadMultiply = 85 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadMinus = 86 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadPlus = 87 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadEnter = 88 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Numpad1 = 89 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Numpad2 = 90 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Numpad3 = 91 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Numpad4 = 92 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Numpad5 = 93 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Numpad6 = 94 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Numpad7 = 95 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Numpad8 = 96 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Numpad9 = 97 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	Numpad0 = 98 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadPeriod = 99 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,

	WindowsContextMenu = 101 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	
	// DedicatedPowerButton = 102 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	
	NumpadEquals = 103 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F13 = 104 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F14 = 105 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F15 = 106 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F16 = 107 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F17 = 108 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F18 = 109 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F19 = 110 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F20 = 111 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F21 = 112 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F22 = 113 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F23 = 114 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	F24 = 115 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	
	// DedicatedExecuteButton = 116 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedHelpButton = 117 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedMenuButton = 118 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedSelectButton = 119 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedStopButton = 120 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedAgainButton = 121 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedUndoButton = 122 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedCutButton = 123 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedCopyButton = 124 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedPasteButton = 125 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedFindButton = 126 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// Mute = 127 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// VolumeUp = 128 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// VolumeDown = 129 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	
	NumpadComma = 133 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	
	// LegacyEquals = 134 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,

	// SysAltErase = 153 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// SysSysReq = 154 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// SysCancel = 155 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// SysClear = 156 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// SysPrior = 157 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// SysReturn2 = 158 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// SysSeparator = 159 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// SysOut = 160 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// SysOper = 161 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// SysClearAgain = 162 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// SysCrSel = 163 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// SysExSel = 164 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,

	NumpadDoubleZero = 176 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadTripleZero = 177 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadThousandsSeparator = 178 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadDecimalsSeparator = 179 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadCurrencyUnit = 180 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadCurrencySubUnit = 181 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadOpeningParenthesis = 182 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadClosingParenthesis = 183 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadOpeningBrace = 184 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadClosingBrace = 185 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadTab = 186 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	NumpadBackspace = 187 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	
	// ProgrammerHexA = 188 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerHexB = 189 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerHexC = 190 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerHexD = 191 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerHexE = 192 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerHexF = 193 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerXor = 194 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerPower = 195 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerPercent = 196 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerLessThan = 197 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerGreaterThan = 198 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerAmpersand = 199 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerDoubleAmpersand = 200 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerVerticalBar = 201 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerDoubleVerticalBar = 202 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerColon = 203 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerHash = 204 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerSpace = 205 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerAt = 206 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerExclaim = 207 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerMemStore = 208 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerMemRecall = 209 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerMemClear = 210 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerMemAdd = 211 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerMemSubtract = 212 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerMemMultiply = 213 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerMemDivide = 214 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerPlusMinus = 215 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerClear = 216 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerClearEntry = 217 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerBinary = 218 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerOctal = 219 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerDecimal = 220 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// ProgrammerHexadecimal = 221 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,

	LeftControl = 224 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	LeftShift = 225 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	LeftAlt = 226 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	LeftWinKey = 227 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	RightControl = 228 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	RightShift = 229 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	RightAlt = 230 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	RightWinKey = 231 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,

	// Mode = 257 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,

	// MediaNext = 258 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// MediaPrevious = 259 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// MediaStop = 260 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// MediaPlay = 261 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// MediaMute = 262 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// MediaSelect = 263 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedWebButton = 264 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedMailButton = 265 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedCalculatorButton = 266 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedMyComputerButton = 267 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedSearchButton = 268 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedHomeButton = 269 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedBackButton = 270 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedForwardButton = 271 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedStopLoadingButton = 272 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedRefreshButton = 273 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedBookmarksButton = 274 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,

	// DisplayBrightnessDown = 275 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DisplayBrightnessUp = 276 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DisplaySwitch = 277 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// KeyboardBacklightToggle = 278 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// KeyboardBacklightDimmer = 279 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// KeyboardBacklightBrighter = 280 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedEjectButton = 281 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedSleepButton = 282 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedApp1Button = 283 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// DedicatedApp2Button = 284 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,

	// MediaRewind = 285 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// MediaFastForward = 286 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,

	// AndroidLeft = 287 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// AndroidRight = 288 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// AndroidStartCall = 289 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
	// AndroidEndCall = 290 | KeyboardKeyExtensions.SdlScancodeToKeycodeBit,
}

public static class KeyboardKeyExtensions {
	internal const int SdlScancodeToKeycodeBit = 1 << 30;
	static readonly KeyboardKeyCategory[] _precomputedCategoryArray = new KeyboardKeyCategory[300];

	static KeyboardKeyExtensions() {
		foreach (var key in Enum.GetValues<KeyboardKey>()) {
			var maskedVal = ((int) key) & ~SdlScancodeToKeycodeBit;
			if (maskedVal < 0 || maskedVal >= _precomputedCategoryArray.Length) throw new InvalidOperationException("Precomputed key category array needs to be larger (or negative value found).");

			_precomputedCategoryArray[maskedVal] = key switch {
				>= KeyboardKey.A and <= KeyboardKey.Z => KeyboardKeyCategory.Alphabetic,
				>= KeyboardKey.NumberRow0 and <= KeyboardKey.NumberRow9 => KeyboardKeyCategory.NumberRow,
				>= KeyboardKey.Space and <= KeyboardKey.Backtick => KeyboardKeyCategory.PunctuationAndSymbology,
				>= KeyboardKey.LeftControl and <= KeyboardKey.RightWinKey => KeyboardKeyCategory.Modifier,
				>= KeyboardKey.ArrowRight and <= KeyboardKey.ArrowUp => KeyboardKeyCategory.Arrow,
				(>= KeyboardKey.Insert and <= KeyboardKey.PageDown) or KeyboardKey.Delete => KeyboardKeyCategory.EditingAndNavigation,
				(>= KeyboardKey.F1 and <= KeyboardKey.F12) or (>= KeyboardKey.F13 and <= KeyboardKey.F24) => KeyboardKeyCategory.Function,
				(>= KeyboardKey.NumpadDivide and <= KeyboardKey.NumpadPeriod) or KeyboardKey.NumpadEquals or KeyboardKey.NumpadComma or (>= KeyboardKey.NumpadDoubleZero and <= KeyboardKey.NumpadBackspace) => KeyboardKeyCategory.Numpad,
				_ => KeyboardKeyCategory.Control
			};
		}
	}

	public static KeyboardKeyCategory GetCategory(this KeyboardKey @this) => _precomputedCategoryArray[((int) @this) & ~SdlScancodeToKeycodeBit];
}