// Created on 2024-08-07 by Ben Bowen
// (c) Egodystonic / TinyFFR 2024

using Egodystonic.TinyFFR.Resources;
using System;
using Egodystonic.TinyFFR.World;

namespace Egodystonic.TinyFFR.Assets.Materials;

/// <summary>
/// An image held in video memory, for use as one of a material's maps or on a <see cref="CanvasScene"/>.
/// </summary>
/// <remarks>
/// <para>
/// A texture's channels do not necessarily hold colour: the same type carries colour maps, normal maps, ORM maps and every other
/// kind, with <see cref="TexelType"/> describing the layout and the material deciding what the values mean.
/// </para>
/// <para>
/// Textures are loaded from image files by the asset loader or generated by the texture builder. Dispose a texture when nothing
/// uses it, and after disposing any material that uses it.
/// </para>
/// </remarks>
public readonly struct Texture : IDisposableResource<Texture, ITextureImplProvider> {
	readonly ResourceHandle<Texture> _handle;
	readonly ITextureImplProvider _impl;

	internal ResourceHandle<Texture> Handle => IsDisposed ? throw new ObjectDisposedException(nameof(Texture)) : _handle;
	internal ITextureImplProvider Implementation => _impl ?? throw InvalidObjectException.InvalidDefault<Texture>();

	ITextureImplProvider IResource<Texture, ITextureImplProvider>.Implementation => Implementation;
	ResourceHandle<Texture> IResource<Texture>.Handle => Handle;
	ResourceIdent IResource.Ident => Handle.Ident;
	IResourceImplProvider IResource.Implementation => Implementation;
	ResourceStub IResource.AsStub => new(Handle.Ident, Implementation);

	/// <summary>
	/// This texture's width and height, in texels.
	/// </summary>
	public XYPair<int> Dimensions {
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get => Implementation.GetDimensions(_handle);
	}

	/// <summary>
	/// The layout of this texture's texels.
	/// </summary>
	public TexelType TexelType {
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get => Implementation.GetTexelType(_handle);
	}

	/// <summary>
	/// Whether this texture's contents may be overwritten after creation.
	/// </summary>
	/// <remarks>
	/// This is fixed when the texture is created. A texture that allows it carries neither mipmaps nor compression, since
	/// neither can be maintained for data that changes.
	/// </remarks>
	public bool AllowsDynamicWrites {
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get => Implementation.GetAllowsDynamicWrites(_handle);
	}
	
	/// <summary>
	/// Whether this texture carries the smaller copies of itself used when it is seen from a distance
	/// (a rendering technique used to improve long-distance views of surfaces at oblique angles).
	/// </summary>
	public bool ContainsMipMaps {
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get => Implementation.GetContainsMipMaps(_handle);
	}
	
	/// <summary>
	/// How this texture is sampled by the GPU.
	/// </summary>
	public TextureRenderingConfig RenderingConfig {
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get => Implementation.GetRenderingConfig(_handle);
	}

	internal Texture(ResourceHandle<Texture> handle, ITextureImplProvider impl) {
		_handle = handle;
		_impl = impl;
	}

	/// <summary>
	/// Replaces this texture's entire contents. <see cref="AllowsDynamicWrites"/> must be <c>true</c> or this method will throw an exception.
	/// </summary>
	/// <remarks>
	/// This is the way to feed changing imagery (a video frame, or a procedurally-generated pattern) to the GPU without
	/// creating a new texture each time.
	/// </remarks>
	/// <typeparam name="TTexel">The type of the texels being supplied.</typeparam>
	/// <param name="newTexels">The replacement texels, laid out row by row (bottom to top). Must hold at least as many entries as this texture has texels.</param>
	/// <exception cref="InvalidOperationException">Thrown when this texture was not created with <see cref="AllowsDynamicWrites"/> set.</exception>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void OverwriteTexels<TTexel>(ReadOnlySpan<TTexel> newTexels) where TTexel : unmanaged, IConversionSupplyingTexel<TTexel, TexelRgb24>, IConversionSupplyingTexel<TTexel, TexelRgba32> {
		OverwriteTexels(newTexels, Dimensions, XYPair<int>.Zero);
	}
	/// <summary>
	/// Replaces a rectangular region of this texture's contents, leaving the rest as it was.
	/// <see cref="AllowsDynamicWrites"/> must be <c>true</c> or this method will throw an exception.
	/// </summary>
	/// <remarks>
	/// Overwriting only the part that changed is cheaper than replacing the whole texture.
	/// </remarks>
	/// <typeparam name="TTexel">The type of the texels being supplied.</typeparam>
	/// <param name="newTexels">The replacement texels for the region, laid out row by row (bottom to top). Must hold at least <c>dimensions.X * dimensions.Y</c> entries.</param>
	/// <param name="dimensions">The width and height of the region being replaced, in texels.</param>
	/// <param name="offset">Where the region begins, measured in texels from the texture's origin. The region must fall entirely within the texture.</param>
	/// <exception cref="InvalidOperationException">Thrown when this texture was not created with <see cref="AllowsDynamicWrites"/> set.</exception>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void OverwriteTexels<TTexel>(ReadOnlySpan<TTexel> newTexels, XYPair<int> dimensions, XYPair<int> offset) where TTexel : unmanaged, IConversionSupplyingTexel<TTexel, TexelRgb24>, IConversionSupplyingTexel<TTexel, TexelRgba32> {
		Implementation.OverwriteTexels(_handle, newTexels, dimensions, offset);
	}

	/// <inheritdoc />
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public string GetNameAsNewStringObject() => Implementation.GetNameAsNewStringObject(_handle);
	/// <inheritdoc />
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public int GetNameLength() => Implementation.GetNameLength(_handle);
	/// <inheritdoc />
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void CopyName(Span<char> destinationBuffer) => Implementation.CopyName(_handle, destinationBuffer);

	static Texture IResource<Texture>.CreateFromHandleAndImpl(ResourceHandle<Texture> handle, IResourceImplProvider impl) {
		return new Texture(handle, impl as ITextureImplProvider ?? throw new InvalidOperationException($"Impl was '{impl}'."));
	}
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	internal ResourceHandle<Texture> GetHandleWithoutDisposeCheck() => _handle;
	ResourceHandle<Texture> IResource<Texture>.GetHandleWithoutDisposeCheck() => GetHandleWithoutDisposeCheck();

	#region Disposal
	/// <summary>
	/// Disposes this texture, releasing its video memory.
	/// </summary>
	/// <remarks>
	/// Every material using this texture must be disposed first.
	/// </remarks>
	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public void Dispose() => Implementation.Dispose(_handle);

	internal bool IsDisposed {
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		get => Implementation.IsDisposed(_handle);
	}
	#endregion

	/// <inheritdoc />
	public override string ToString() => $"Texture {(IsDisposed ? "(Disposed)" : $"\"{GetNameAsNewStringObject()}\"")}";

	#region Equality
	/// <inheritdoc />
	public bool Equals(Texture other) => _handle == other._handle && ReferenceEquals(_impl, other._impl);
	/// <inheritdoc />
	public override bool Equals(object? obj) => obj is Texture other && Equals(other);
	/// <inheritdoc />
	public override int GetHashCode() => HashCode.Combine(_handle, _impl);
	/// <summary>
	/// Returns whether the two given textures are the same texture.
	/// </summary>
	/// <param name="left">The first texture to compare.</param>
	/// <param name="right">The second texture to compare.</param>
	public static bool operator ==(Texture left, Texture right) => left.Equals(right);
	/// <summary>
	/// Returns whether the two given textures are different textures.
	/// </summary>
	/// <param name="left">The first texture to compare.</param>
	/// <param name="right">The second texture to compare.</param>
	public static bool operator !=(Texture left, Texture right) => !left.Equals(right);
	#endregion
}